### ISSUE TITLE
Possible improvements, housekeeping

### ISSUE THREAD

**Issue by slhck** [varenc/homebrew-ffmpeg#9]
Based on Lou Logan's comments:

- `--enable-avresample` really needed?
- `--enable-librtmp` can be removed
- `--enable-libxvid` can be removed
- `--enable-libspeex` is obsolete, replaced by Opus
- `--enable-hardcoded-tables` – might be time to drop that if it makes no significant difference if someone wants to test
- Figure out how to deal with `libjack` – should it be optional under Linux?

My suggestion would be to:

- [x] Keep librtmp, but make it optional  => #15
- [x] Keep libxvid, but make it optional => #13 
- [x] Keep libspeex, but make it optional => #14 
- [ ] Check usage of `avresample`
- [ ] Add support for `libjack` => #16
- [x] Keep hardcoded tables, but have to further investigate --> done by Reto.

**Comment by retokromer** [comment]
We do actually use `--enable-hardcoded-tables`, but if it’s an option (not enabled by default), then it’s fine on our side.

**Comment by slhck** [comment]
First three libraries are done. For Jack, still waiting due to an issue with pkg_config in Linuxbrew.

I haven't had time to look into avresample and the hardcoded tables, I guess these can be kept as-is, too.

**Comment by retokromer** [comment]
FYI: this repository should be [added](https://github.com/Homebrew/brew/pull/5818/commits/e295570f00536f65375b74ef732a28b9c76d3997) soon to Homebrew’s list of interesting taps.

**Update:** [merged](https://github.com/Homebrew/brew/commit/cf354e7b9d15af0a65020660dbfba88011862d73)

**Comment by slhck** [comment]
Great, thanks for the heads-up!

**Comment by retokromer** [comment]
@slhck FYI: I did delete the hardcoded tables in https://github.com/varenc/homebrew-ffmpeg/pull/34.

**Comment by vcunat** [comment]
Any idea/reference why that flag started causing issues? (on Linux as well)

**Comment by retokromer** [comment]
>Any idea/reference why that flag started causing issues? (on Linux as well)


http://git.ffmpeg.org/gitweb/ffmpeg.git/commit/c8232e50074f6f9f9b0674d0a5433f49d73a4e50
